[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "https://southernsunshineandroses.netlify.com/blog.html"
  status = 301
  force = true
[[redirects]]
  from = "/about"
  to = "https://southernsunshineandroses.netlify.com/about.html"
  status = 301
  force = true