[build]
  command = "npm install && npm run build"
  functions = "functions"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/blog.html"
  status = 301
  force = true
[[redirects]]
  from = "https://southernsunshineandroses.netlify.com/about"
  to = "https://southernsunshineandroses.netlify.com/about.html"
  status = 301
  force = true