[build]
  command = "npm install && npm run build"
  functions = "functions"
[[redirects]]
  from = "/blog"
  to = "/blog"
  status = 301
  force = true
[[redirects]]
  from = "/about"
  to = "/about"
  status = 301
  force = true